spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/spring
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hiberniate:
        dialect: org.hibernate.dialect.MySQL8Dilect
        format_sql: true
    show-sql: true